/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyNotesRouteImport } from './routes/study-notes'
import { Route as StudyRouteImport } from './routes/study'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as ExtraLessonsIndexRouteImport } from './routes/extra-lessons.index'
import { Route as StudyVocabRouteImport } from './routes/study.vocab'
import { Route as StudyQuizRouteImport } from './routes/study.quiz'
import { Route as StudyPronunciationRouteImport } from './routes/study.pronunciation'
import { Route as StudyDrivingRouteImport } from './routes/study.driving'
import { Route as StudyDialoguesRouteImport } from './routes/study.dialogues'
import { Route as StudyBookmarksRouteImport } from './routes/study.bookmarks'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as ExtraLessonsExtraLessonIdRouteImport } from './routes/extra-lessons.$extraLessonId'

const StudyNotesRoute = StudyNotesRouteImport.update({
  id: '/study-notes',
  path: '/study-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudyRoute,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtraLessonsIndexRoute = ExtraLessonsIndexRouteImport.update({
  id: '/extra-lessons/',
  path: '/extra-lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyVocabRoute = StudyVocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => StudyRoute,
} as any)
const StudyQuizRoute = StudyQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => StudyRoute,
} as any)
const StudyPronunciationRoute = StudyPronunciationRouteImport.update({
  id: '/pronunciation',
  path: '/pronunciation',
  getParentRoute: () => StudyRoute,
} as any)
const StudyDrivingRoute = StudyDrivingRouteImport.update({
  id: '/driving',
  path: '/driving',
  getParentRoute: () => StudyRoute,
} as any)
const StudyDialoguesRoute = StudyDialoguesRouteImport.update({
  id: '/dialogues',
  path: '/dialogues',
  getParentRoute: () => StudyRoute,
} as any)
const StudyBookmarksRoute = StudyBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => StudyRoute,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtraLessonsExtraLessonIdRoute =
  ExtraLessonsExtraLessonIdRouteImport.update({
    id: '/extra-lessons/$extraLessonId',
    path: '/extra-lessons/$extraLessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/study': typeof StudyRouteWithChildren
  '/study-notes': typeof StudyNotesRoute
  '/extra-lessons/$extraLessonId': typeof ExtraLessonsExtraLessonIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/study/bookmarks': typeof StudyBookmarksRoute
  '/study/dialogues': typeof StudyDialoguesRoute
  '/study/driving': typeof StudyDrivingRoute
  '/study/pronunciation': typeof StudyPronunciationRoute
  '/study/quiz': typeof StudyQuizRoute
  '/study/vocab': typeof StudyVocabRoute
  '/extra-lessons/': typeof ExtraLessonsIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/study-notes': typeof StudyNotesRoute
  '/extra-lessons/$extraLessonId': typeof ExtraLessonsExtraLessonIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/study/bookmarks': typeof StudyBookmarksRoute
  '/study/dialogues': typeof StudyDialoguesRoute
  '/study/driving': typeof StudyDrivingRoute
  '/study/pronunciation': typeof StudyPronunciationRoute
  '/study/quiz': typeof StudyQuizRoute
  '/study/vocab': typeof StudyVocabRoute
  '/extra-lessons': typeof ExtraLessonsIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/study': typeof StudyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/study': typeof StudyRouteWithChildren
  '/study-notes': typeof StudyNotesRoute
  '/extra-lessons/$extraLessonId': typeof ExtraLessonsExtraLessonIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/study/bookmarks': typeof StudyBookmarksRoute
  '/study/dialogues': typeof StudyDialoguesRoute
  '/study/driving': typeof StudyDrivingRoute
  '/study/pronunciation': typeof StudyPronunciationRoute
  '/study/quiz': typeof StudyQuizRoute
  '/study/vocab': typeof StudyVocabRoute
  '/extra-lessons/': typeof ExtraLessonsIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/study'
    | '/study-notes'
    | '/extra-lessons/$extraLessonId'
    | '/lessons/$lessonId'
    | '/study/bookmarks'
    | '/study/dialogues'
    | '/study/driving'
    | '/study/pronunciation'
    | '/study/quiz'
    | '/study/vocab'
    | '/extra-lessons/'
    | '/lessons/'
    | '/study/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/study-notes'
    | '/extra-lessons/$extraLessonId'
    | '/lessons/$lessonId'
    | '/study/bookmarks'
    | '/study/dialogues'
    | '/study/driving'
    | '/study/pronunciation'
    | '/study/quiz'
    | '/study/vocab'
    | '/extra-lessons'
    | '/lessons'
    | '/study'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/study'
    | '/study-notes'
    | '/extra-lessons/$extraLessonId'
    | '/lessons/$lessonId'
    | '/study/bookmarks'
    | '/study/dialogues'
    | '/study/driving'
    | '/study/pronunciation'
    | '/study/quiz'
    | '/study/vocab'
    | '/extra-lessons/'
    | '/lessons/'
    | '/study/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  StudyRoute: typeof StudyRouteWithChildren
  StudyNotesRoute: typeof StudyNotesRoute
  ExtraLessonsExtraLessonIdRoute: typeof ExtraLessonsExtraLessonIdRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  ExtraLessonsIndexRoute: typeof ExtraLessonsIndexRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-notes': {
      id: '/study-notes'
      path: '/study-notes'
      fullPath: '/study-notes'
      preLoaderRoute: typeof StudyNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof StudyRoute
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extra-lessons/': {
      id: '/extra-lessons/'
      path: '/extra-lessons'
      fullPath: '/extra-lessons/'
      preLoaderRoute: typeof ExtraLessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/vocab': {
      id: '/study/vocab'
      path: '/vocab'
      fullPath: '/study/vocab'
      preLoaderRoute: typeof StudyVocabRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/quiz': {
      id: '/study/quiz'
      path: '/quiz'
      fullPath: '/study/quiz'
      preLoaderRoute: typeof StudyQuizRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/pronunciation': {
      id: '/study/pronunciation'
      path: '/pronunciation'
      fullPath: '/study/pronunciation'
      preLoaderRoute: typeof StudyPronunciationRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/driving': {
      id: '/study/driving'
      path: '/driving'
      fullPath: '/study/driving'
      preLoaderRoute: typeof StudyDrivingRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/dialogues': {
      id: '/study/dialogues'
      path: '/dialogues'
      fullPath: '/study/dialogues'
      preLoaderRoute: typeof StudyDialoguesRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/bookmarks': {
      id: '/study/bookmarks'
      path: '/bookmarks'
      fullPath: '/study/bookmarks'
      preLoaderRoute: typeof StudyBookmarksRouteImport
      parentRoute: typeof StudyRoute
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extra-lessons/$extraLessonId': {
      id: '/extra-lessons/$extraLessonId'
      path: '/extra-lessons/$extraLessonId'
      fullPath: '/extra-lessons/$extraLessonId'
      preLoaderRoute: typeof ExtraLessonsExtraLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudyRouteChildren {
  StudyBookmarksRoute: typeof StudyBookmarksRoute
  StudyDialoguesRoute: typeof StudyDialoguesRoute
  StudyDrivingRoute: typeof StudyDrivingRoute
  StudyPronunciationRoute: typeof StudyPronunciationRoute
  StudyQuizRoute: typeof StudyQuizRoute
  StudyVocabRoute: typeof StudyVocabRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyBookmarksRoute: StudyBookmarksRoute,
  StudyDialoguesRoute: StudyDialoguesRoute,
  StudyDrivingRoute: StudyDrivingRoute,
  StudyPronunciationRoute: StudyPronunciationRoute,
  StudyQuizRoute: StudyQuizRoute,
  StudyVocabRoute: StudyVocabRoute,
  StudyIndexRoute: StudyIndexRoute,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  StudyRoute: StudyRouteWithChildren,
  StudyNotesRoute: StudyNotesRoute,
  ExtraLessonsExtraLessonIdRoute: ExtraLessonsExtraLessonIdRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  ExtraLessonsIndexRoute: ExtraLessonsIndexRoute,
  LessonsIndexRoute: LessonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
