/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as StudyVocabRouteImport } from './routes/study.vocab'
import { Route as StudyQuizRouteImport } from './routes/study.quiz'
import { Route as StudyDialoguesRouteImport } from './routes/study.dialogues'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudyRoute,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyVocabRoute = StudyVocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => StudyRoute,
} as any)
const StudyQuizRoute = StudyQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => StudyRoute,
} as any)
const StudyDialoguesRoute = StudyDialoguesRouteImport.update({
  id: '/dialogues',
  path: '/dialogues',
  getParentRoute: () => StudyRoute,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/study': typeof StudyRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/study/dialogues': typeof StudyDialoguesRoute
  '/study/quiz': typeof StudyQuizRoute
  '/study/vocab': typeof StudyVocabRoute
  '/lessons/': typeof LessonsIndexRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/study/dialogues': typeof StudyDialoguesRoute
  '/study/quiz': typeof StudyQuizRoute
  '/study/vocab': typeof StudyVocabRoute
  '/lessons': typeof LessonsIndexRoute
  '/study': typeof StudyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/study': typeof StudyRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/study/dialogues': typeof StudyDialoguesRoute
  '/study/quiz': typeof StudyQuizRoute
  '/study/vocab': typeof StudyVocabRoute
  '/lessons/': typeof LessonsIndexRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/study'
    | '/lessons/$lessonId'
    | '/study/dialogues'
    | '/study/quiz'
    | '/study/vocab'
    | '/lessons/'
    | '/study/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lessons/$lessonId'
    | '/study/dialogues'
    | '/study/quiz'
    | '/study/vocab'
    | '/lessons'
    | '/study'
  id:
    | '__root__'
    | '/'
    | '/study'
    | '/lessons/$lessonId'
    | '/study/dialogues'
    | '/study/quiz'
    | '/study/vocab'
    | '/lessons/'
    | '/study/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudyRoute: typeof StudyRouteWithChildren
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof StudyRoute
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/vocab': {
      id: '/study/vocab'
      path: '/vocab'
      fullPath: '/study/vocab'
      preLoaderRoute: typeof StudyVocabRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/quiz': {
      id: '/study/quiz'
      path: '/quiz'
      fullPath: '/study/quiz'
      preLoaderRoute: typeof StudyQuizRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/dialogues': {
      id: '/study/dialogues'
      path: '/dialogues'
      fullPath: '/study/dialogues'
      preLoaderRoute: typeof StudyDialoguesRouteImport
      parentRoute: typeof StudyRoute
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudyRouteChildren {
  StudyDialoguesRoute: typeof StudyDialoguesRoute
  StudyQuizRoute: typeof StudyQuizRoute
  StudyVocabRoute: typeof StudyVocabRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyDialoguesRoute: StudyDialoguesRoute,
  StudyQuizRoute: StudyQuizRoute,
  StudyVocabRoute: StudyVocabRoute,
  StudyIndexRoute: StudyIndexRoute,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudyRoute: StudyRouteWithChildren,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  LessonsIndexRoute: LessonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
